//
//  ListPokemonModels.swift
//  SimpleVIP
//
//  Created by FauziArda on 21/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListPokemon
{
  // MARK: Use cases
  
  enum FetchPokemons
  {
    struct Request
    {
        var id: Int
    }
    struct Response: Decodable
    {
        var pokemons: [Pokemon]
        
        enum CodingKeys: String, CodingKey {
                case pokemons = "results"
            }
    }
    struct ViewModel
    {
        struct DisplayedPokemon{
            var id: Int
            var name: String
            var imageURL: URL
        }
        
        var displayedPokemons: [DisplayedPokemon]
    }
  }
}
