//
//  FirstSceneInteractor.swift
//  SimpleVIP
//
//  Created by Batm Admin on 21/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPokemonBusinessLogic{
    func fetchPokemons(request: ListPokemon.FetchPokemons.Request)
    
}

protocol ListPokemonDataStore{
    var pokemons: [Pokemon]? {get set}
    func updatePokemon()
}

class ListPokemonInteractor: ListPokemonBusinessLogic, ListPokemonDataStore{
    var presenter: ListPokemonPresentationLogic?
    var pokemonWorker: PokemonsWorker = PokemonsWorker(pokemonsStore: PokemonsAPIStore())
    var pokemons: [Pokemon]?
 
    // MARK: fetchPokemons
    func fetchPokemons(request: ListPokemon.FetchPokemons.Request) {
        pokemonWorker.fetchPokemons {  pokemons in
            self.pokemons = pokemons
            self.presenter?.presentFetchedPokemons(response: ListPokemon.FetchPokemons.Response(pokemons: pokemons))
        }
    }
    
    func updatePokemon() {
        self.presenter?.presentFetchedPokemons(response: ListPokemon.FetchPokemons.Response(pokemons: self.pokemons!))
    }
}
