//
//  ListPokemonPresenter.swift
//  SimpleVIP
//
//  Created by Batm Admin on 21/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPokemonPresentationLogic
{
    func presentSomething(response: ListPokemon.FetchPokemons.Response)
    func presentFetchedPokemons(response: ListPokemon.FetchPokemons.Response)
}

class ListPokemonPresenter: ListPokemonPresentationLogic
{
    
  weak var viewController: ListPokemonDisplayLogic?
  
  // MARK: Do something
  
    func presentFetchedPokemons(response: ListPokemon.FetchPokemons.Response)
  {
      // prepare data to be send to view
      var displayedPokemons = [ListPokemon.FetchPokemons.ViewModel.DisplayedPokemon]()
      for pokemon in response.pokemons {
          guard let url = URL(string: pokemon.imageUrl) else {return}
          var displayedPokemon = ListPokemon.FetchPokemons.ViewModel.DisplayedPokemon(id: pokemon.id, name: pokemon.name, imageURL: url)
          displayedPokemons.append(displayedPokemon)
      }
      
      let viewModel = ListPokemon.FetchPokemons.ViewModel(displayedPokemons: displayedPokemons)
      viewController?.displayPokemons(viewModel: viewModel)
  }
    
    func presentSomething(response: ListPokemon.FetchPokemons.Response) {
        // do something
    }
    
    
}
