//
//  ListPokemonRouter.swift
//  SimpleVIP
//
//  Created by FauziArda on 21/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListPokemonRoutingLogic
{
  func routeToPokemonDetail()
}

protocol ListPokemonDataPassing
{
  var dataStore: ListPokemonDataStore? { get }
}

class ListPokemonRouter: NSObject, ListPokemonRoutingLogic, ListPokemonDataPassing
{
  weak var viewController: ListPokemonViewController?
  var dataStore: ListPokemonDataStore?
  
  // MARK: Routing
  func routeToPokemonDetail()
  {
      let destinationVC = PokemonDetailViewController()
      var destinationDS = destinationVC.router!.dataStore!
      passDataToPokemonDetail(source: dataStore!, destination: &destinationDS)
      navigateToPokemonDetail(source: viewController!, destination: destinationVC)
    
  }

  // MARK: Navigation
  func navigateToPokemonDetail(source: ListPokemonViewController, destination: PokemonDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToPokemonDetail(source: ListPokemonDataStore, destination: inout PokemonDetailDataStore)
  {
      let selectedRow = self.viewController?.tableView.indexPathForSelectedRow?.row
      destination.pokemon = source.pokemons![selectedRow!]
  }
}
