//
//  ListPokemonWorker.swift
//  SimpleVIP
//
//  Created by FauziArda on 21/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListPokemonWorker
{
  func doSomeWork()
  {
  }
    
//    func fetchPokemons(_ id: Int = 0, success: @escaping(([ListPokemon.FetchPokemons.Response])->Void), fail: @escaping((String)->Void)){
//        // TODO: create data manager/repository/usecases for data sources
//        let response = ListPokemonMock.ResponseMock.data() as! [ListPokemon.FetchPokemons.Response]
//
//        if response.count > 0 {
//            success(response)
//        }else{
//            fail("Error")
//        }
//
//    }
}
