//
//  PokemonDetailRouter.swift
//  SimpleVIP
//
//  Created by FauziArda on 22/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PokemonDetailRoutingLogic
{
    func routeToListPokemon()
}

protocol PokemonDetailDataPassing
{
  var dataStore: PokemonDetailDataStore? { get }
}

class PokemonDetailRouter: NSObject, PokemonDetailRoutingLogic, PokemonDetailDataPassing
{
  weak var viewController: PokemonDetailViewController?
  var dataStore: PokemonDetailDataStore?
  
  // MARK: Routing
  
  func routeToListPokemon()
  {
    
      let index = viewController!.navigationController!.viewControllers.count - 2
      let destinationVC = viewController?.navigationController?.viewControllers[index] as! ListPokemonViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToListPokemon(source: dataStore!, destination: &destinationDS)
      navigateToListPokemon(source: viewController!, destination: destinationVC)
    
  }

  // MARK: Navigation
  
  func navigateToListPokemon(source: PokemonDetailViewController, destination: ListPokemonViewController)
  {
    source.navigationController?.popViewController(animated: true)
  }
  
  // MARK: Passing data
  
func passDataToListPokemon(source: PokemonDetailDataStore, destination: inout ListPokemonDataStore)
  {
      if let row = destination.pokemons?.firstIndex(where: {$0.id == source.pokemon.id}){
          destination.pokemons![row].name = source.pokemon.name
      }
      destination.updatePokemon()
  }
}
