//
//  PokemonDetailModels.swift
//  SimpleVIP
//
//  Created by FauziArda on 22/02/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PokemonDetail
{
  // MARK: Use cases
  
  enum FetchDetail
  {
    struct Request
    {
    }
      struct Response : Decodable
    {
        var data: PokemonData
    }
    struct ViewModel
    {
        struct DisplayPokemonDetail{
            var name: String
            var id: Int
            var height: Int
            var moves: [String]
            var abilites: [String]
            var species: String
            var types: [String]
            var weight: Int
             
        }
        
        var pokemonDetail:  DisplayPokemonDetail
    }
  }
    
    enum UpdateName{
        struct Request{
            var name : String
        }
        struct Response{
            
        }
        struct ViewModel{
            
        }
    }
}
